from __future__ import annotations

from pathlib import Path
from .catalog import get_catalog

def render_reference() -> str:
    catalog = get_catalog()
    lines = ["# Semantic Catalog Reference", "", "<!-- generated by: uv run python -m semantic_layer.generate_reference -->", "", "This reference is generated from versioned JSON definitions; do not edit the tables manually.", "", "## Metrics", "", "| ID | Display name | Kind | Operations | Period mode | Dimensions | Primary tools | Supporting tools | Proxy | Limitations |", "|---|---|---|---|---|---|---|---|---|---|"]
    for metric in catalog.list_metrics():
        lines.append("| " + " | ".join([metric.metric_id, metric.display_name, metric.metric_kind, ", ".join(metric.supported_operations), metric.required_period_mode, ", ".join(metric.allowed_dimensions), ", ".join(metric.primary_tools), ", ".join(metric.supporting_tools), "yes" if metric.is_proxy else "no", "; ".join(metric.limitations)]) + " |")
    lines += ["", "## Task coverage", "", "| task_type | requirement | runtime path | coverage | limitation |", "|---|---|---|---|---|"]
    for entry in catalog.list_task_coverage():
        requirement = catalog.get_task_requirement(entry.task_type)
        lines.append(f"| {entry.task_type} | {requirement.requirement_id if requirement else '-'} | {entry.runtime_path} | {entry.coverage_status} | {entry.required_limitation} |")
    return "\n".join(lines) + "\n"

def main() -> None:
    Path("docs/SEMANTIC_CATALOG_REFERENCE.md").write_text(render_reference(), encoding="utf-8")

if __name__ == "__main__": main()
